config/routes.rb
Babysworld::Application.routes.draw do
  root :to => "products#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :skip => [:sessions], controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get '/about', to: 'welcome#about'
  get '/terms', to: 'welcome#terms'
  get '/user_consignment', to: 'welcome#user_consignment'
  get '/consignment_about', to: 'welcome#consignment_about'
  get '/faq', to: 'welcome#faq'
  get '/robots.txt', to: 'welcome#robots'

  get 'tags/:tag', to: 'products#index', as: :tag

  namespace :admin do
    resources :products do
      put '/release', to: 'products#release'
      put '/waiting_for_money', to: 'products#waiting_for_money'
      put '/sold', to: 'products#sold'
    end
    resources :banners
    resources :consignments
    resources :consignment_products do
      put '/deny', to: 'consignment_products#deny'
      resources :products, controller: 'consignment_products/products'
    end
    resources :billings
  end

  resources :users, only: [:edit, :update] do
    resources :billings, only: [:create, :index]
  end

  resources :billings do
    resources :consignment_products, only: [:index]
  end

  resources :products, :only => [:index, :show]

  resources :consignments
  resources :consignment_products do
    put '/billing', to: 'consignment_products#billing'
  end

end

app/views/shared/_disinfection.html.slim
h4.alert-heading 安全衛生
span 賣場中所有的託售商品都會先經過飛利浦紫外線消毒殺菌燈進行消毒作業，消毒作業完成後才會進行上架作業，不僅僅是我們對於寶寶衛生安全的負責任態度，也希望能讓各位爸比媽咪也都能買得更安心。

app/views/shared/_error_messages.html.slim
- if target.errors.any?
  div id="errorExplanation"
    h2
      = t('action.error_before_save_form', :count => target.errors.count)
    ul
      - target.errors.full_messages.each do |msg|
        li= msg

app/views/shared/_sidebar_link.html.slim
#faqs data-spy="affix"
  ul.faqs
    li.bg_white= link_to '託售規則', '/user_consignment'
    li.bg_white= link_to '託售所得計算', 'user_consignment#calculate'
    li.bg_white= link_to '拒收商品', 'user_consignment#deny'
    li.bg_white= link_to '託售流程', 'user_consignment#process'
    li.bg_white= link_to '常見問題Q&A', '/faq'

app/views/shared/_tags_aside.html.slim
#tags
  h4
    i.icon.icon-folder-close
    '
    | 分類
  ul.tags
    - @tags.each_with_index do |p, index|
      - if index.even?
        li.bg_white
          = link_to p.name, tag_path(p.name)
      - else
        li
          = link_to p.name, tag_path(p.name)

app/views/shared/_user_status_panel.html.slim
li= link_to "託售須知", '/user_consignment'
li= link_to '我要託售商品', '/consignment_about'
- if current_admin
  li= link_to "管理者後台", admin_products_path, :target => "_blank"
- if current_user
  li.dropdown
    = link_to "#", class: 'dropdown-toggle', data: { 'toggle' => 'dropdown' } do
      span #{current_user.username}
      b.caret
    ul.dropdown-menu
      li= link_to "我的資料", edit_user_path(current_user)
      li= link_to "我的託售記錄", consignments_path
      li= link_to "我的請款記錄", user_billings_path(current_user)
      li= link_to "登出", destroy_user_session_path, :method => :delete
- else
  li= link_to "註冊", new_user_registration_path
  li= link_to "登入", new_user_session_path