config/routes.rb
Babysworld::Application.routes.draw do
  root :to => "products#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :skip => [:sessions], controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get '/about', to: 'welcome#about'
  get '/terms', to: 'welcome#terms'
  get '/user_consignment', to: 'welcome#user_consignment'
  get '/consignment_about', to: 'welcome#consignment_about'
  get '/faq', to: 'welcome#faq'
  get '/robots.txt', to: 'welcome#robots'

  get 'tags/:tag', to: 'products#index', as: :tag

  namespace :admin do
    resources :products do
      put '/release', to: 'products#release'
      put '/waiting_for_money', to: 'products#waiting_for_money'
      put '/sold', to: 'products#sold'
    end
    resources :banners
    resources :consignments
    resources :consignment_products do
      put '/deny', to: 'consignment_products#deny'
      resources :products, controller: 'consignment_products/products'
    end
    resources :billings
  end

  resources :users, only: [:edit, :update] do
    resources :billings, only: [:create, :index]
  end

  resources :billings do
    resources :consignment_products, only: [:index]
  end

  resources :products, :only => [:index, :show]

  resources :consignments
  resources :consignment_products do
    put '/billing', to: 'consignment_products#billing'
  end

end

app/models/product.rb
#encoding: utf-8
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :original_price, :price, :ruten_no, :user,
                  :status, :product_images_attributes, :pattern, :notice,
                  :category_id, :tag_list
  belongs_to :user
  belongs_to :category
  has_many :product_images, :dependent => :destroy
  accepts_nested_attributes_for :product_images, :reject_if => :all_blank, :allow_destroy => true
  validates_presence_of :name, :description, :user, :price,
                        :ruten_no
  acts_as_taggable
  has_one :consignment_product
  delegate :name, to: :consignment_product, allow_nil: true, prefix: true
  validate :at_least_one_image

  default_scope :order => 'created_at desc'

  STATUS =  {
             "waiting_for_review" => "等待上架",
             "released" => "已上架",
             "replenish" => "補貨中",
             "checked_out" => "已售出"
            }

  state_machine :status, :initial => :waiting_for_review do
    event :release do
      transition [:waiting_for_review, :replenish] => :released
    end

    event :waiting_for_money do
      transition :released => :replenish
    end

    event :sold do
      transition :replenish => :checked_out
    end

    after_transition [:waiting_for_review, :replenish] => :released do |product|
      product.consignment_product.release if product.consignment_product.present?
    end

    after_transition :released => :replenish do |product|
      product.consignment_product.ordered if product.consignment_product.present?
    end

    after_transition :replenish => :checked_out do |product|
      product.consignment_product.sold if product.consignment_product.present?
    end

  end

  extend Category::FindByCategoryScope

  validates_inclusion_of :status, :in => STATUS.keys

  scope :available, where(:status => ["released", "replenish"])

  def url
    "http://goods.ruten.com.tw/item/show?#{self.ruten_no}"
  end

  def self.search(query)
    where("name LIKE ? OR description LIKE ?", "%#{query}%", "%#{query}%")
  end

  private

  def at_least_one_image
    errors.add(:product_images, "至少要有一張圖片") if product_images.length == 0
  end
end

app/controllers/admin/consignment_products/products_controller.rb
#encoding: utf-8
class Admin::ConsignmentProducts::ProductsController < ApplicationController
  before_filter :authenticate_admin
  layout 'admin'

  def new
    @consignment_product = ConsignmentProduct.find(params[:consignment_product_id])
    @product = @consignment_product.to_product
  end

  def create
    consignment_product = ConsignmentProduct.find(params[:consignment_product_id])
    @product = consignment_product.build_product(params[:product])
    @product.user = current_user
    if @product.save
      consignment_product.save
      redirect_to admin_products_path, notice: '建立成功'
    else
      render :new, error: @product.errors
    end
  end
end

app/controllers/admin/products_controller.rb
#encoding: utf-8
class Admin::ProductsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin

  def index
    @products = Product.paginate(:page => params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = current_user.products.build
    @product.product_images.build
  end

  def create
    @product = current_user.products.build(params[:product])

    if @product.save
      redirect_to admin_products_path, :notice => "商品建立成功"
    else
      ap @product.errors
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(params[:product])
      redirect_to admin_products_path, :notice => "商品修改成功"
    else
      render :edit
    end
  end

  def release
    @product = Product.find(params[:product_id])
    if @product.release
      redirect_to admin_products_path, notice: '商品狀態變更為已上架'
    else
      redirect_to admin_products_path, error: "商品狀態變更失敗，原因:#{@product.errors}"
    end
  end

  def waiting_for_money
    @product = Product.find(params[:product_id])
    if @product.waiting_for_money
      redirect_to admin_products_path, notice: '商品狀態變更為補貨中'
    else
      redirect_to admin_products_path, error: "商品狀態變更失敗，原因:#{@product.errors}"
    end
  end

  def sold
    @product = Product.find(params[:product_id])
    if @product.sold
      redirect_to admin_products_path, notice: '商品狀態變更為已售出'
    else
      redirect_to admin_products_path, error: "商品狀態變更失敗，原因:#{@product.errors}"
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    if params[:tag]
      @products = Product.available.tagged_with(params[:tag]).paginate(:page => params[:page])
    elsif params[:search]
      @products = Product.available.search(params[:search]).paginate(:page => params[:page], per_page: 15)
    else
      @products = Product.available.paginate(:page => params[:page], per_page: 15)
    end
    @banners = Banner.available
  end

  def show
    @product = Product.available.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def currency_format(amount)
    number_to_currency amount, precision: 0
  end

  def render_product_btn(product)
    case product.status
    when 'waiting_for_review'
      then link_to '上架', admin_product_release_path(product), method: :put, class: 'btn btn-mini btn-success'
    when 'released'
      then link_to('補貨', admin_product_waiting_for_money_path(product), method: :put, class: 'btn btn-mini btn-success')
    when 'replenish'
      then link_to('售出', admin_product_sold_path(product), method: :put, class: 'btn btn-mini btn-success')+ " | " + link_to('重新上架', admin_product_release_path(product), method: :put, class: 'btn btn-mini btn-primary')
    else
      ""
    end
  end
end

app/views/admin/products/_form.html.slim
= simple_form_for([:admin, @product], :html => { :class => 'form-horizontal' }) do |f|
  = f.input :name, :label => "商品名稱", :input_html => { :class => "span10" }
  = f.input :description, :label => "商品描述", :input_html => { :class => "span10" }
  = f.input :notice, :label => "注意事項", :input_html => { :class => "span10" }
  = f.simple_fields_for :product_images do |product_image|
    = render 'product_image_fields', f: product_image
  .controls
    = link_to_add_association '新增一張圖片', f, :product_images, class: 'btn btn-success btn-flat btn-small'
  = f.input :tag_list, :label => "分類(可使用逗點分隔指定多個分類)", :input_html => { :class => "span10" }
  = f.input :original_price, :label => "市價", :input_html => { :class => "span10" }
  = f.input :price, :label => "售價", :input_html => { :class => "span10" }
  = f.input :ruten_no, :label => "露天編號", :input_html => { :class => "span10" }
  .form-actions
    = f.submit "儲存", :class => 'btn btn-primary'

app/views/admin/products/_product_image_fields.html.slim
.nested-fields.well
  = f.input :image, as: :image_preview, label: false, input_html: { preview_version: :thumb, class: 'fancy' }
  = link_to_remove_association '移除這張圖片', f, class: 'btn btn-danger btn-mini'

app/views/admin/products/edit.html.slim
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container style="width: auto;"
            a.brand href="#" 編輯 #{@product.name}
      #product_form
        = render :partial => 'form'

app/views/admin/products/index.html.slim
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container style="width: auto;"
            a.brand href="#" 商品列表
      #products_wrapper
        table.table.table-striped.table-bordered.table-condensed
          thead
            tr
              th 商品編號
              th 商品分類
              th 商品名稱
              th 原託售商品
              th 原價
              th 售價
              th 露天編號
              th 狀態
              th 狀態操作
              th 建立時間
              th 更新時間
              th 操作
          tbody
            - @products.each do |product|
              tr
                td= product.id
                td= raw product.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')
                td= link_to product.name, admin_product_path(product)
                td= link_to product.consignment_product_name, admin_consignment_product_path(product.consignment_product) if product.consignment_product
                td= product.original_price
                td= product.price
                td= link_to product.ruten_no, product.url
                td= Product::STATUS[product.status]
                td= render_product_btn(product)
                td= l product.created_at, :format => :short
                td= l product.updated_at, :format => :short
                td
                  = link_to edit_admin_product_path(product), :class => 'btn' do
                    = content_tag(:i, '', :class => 'icon icon-edit')
                    '  編輯
      = will_paginate @products

app/views/admin/products/new.html.slim
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container style="width: auto;"
            a.brand href="#" 新增商品
      #product_form
        = render :partial => 'form'