config/routes.rb
Babysworld::Application.routes.draw do
  root :to => "products#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :skip => [:sessions], controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get '/about', to: 'welcome#about'
  get '/terms', to: 'welcome#terms'
  get '/user_consignment', to: 'welcome#user_consignment'
  get '/consignment_about', to: 'welcome#consignment_about'
  get '/faq', to: 'welcome#faq'
  get '/robots.txt', to: 'welcome#robots'

  get 'tags/:tag', to: 'products#index', as: :tag

  namespace :admin do
    resources :products do
      put '/release', to: 'products#release'
      put '/waiting_for_money', to: 'products#waiting_for_money'
      put '/sold', to: 'products#sold'
    end
    resources :banners
    resources :consignments
    resources :consignment_products do
      put '/deny', to: 'consignment_products#deny'
      resources :products, controller: 'consignment_products/products'
    end
    resources :billings
  end

  resources :users, only: [:edit, :update] do
    resources :billings, only: [:create, :index]
  end

  resources :billings do
    resources :consignment_products, only: [:index]
  end

  resources :products, :only => [:index, :show]

  resources :consignments
  resources :consignment_products do
    put '/billing', to: 'consignment_products#billing'
  end

end

app/models/consignment.rb
#encoding: utf-8
class Consignment < ActiveRecord::Base
  attr_accessible :address, :phone, :status, :user_id, :chinese_name,
                  :consignment_products_attributes, :bank, :bank_num,
                  :account, :account_num, :balance
  belongs_to :user
  has_many :consignment_products

  after_save :save_user_info
  after_create :notice_admin

  accepts_nested_attributes_for :consignment_products, allow_destroy: true

  validates_presence_of :address, :phone, :chinese_name, :account, :bank, :account_num, :bank_num

  def save_user_info
    if phone != user.phone || address != user.address || chinese_name != user.chinese_name
      user.update_attributes(address: address,
                             chinese_name: chinese_name,
                             phone: phone)
    elsif bank != user.bank || account != user.account || bank_num != user.bank_num || account_num != user.account_num
      user.update_attributes(bank: bank,
                             account: account,
                             bank_num: bank_num,
                             account_num: account_num)
    end
  end

  def notice_admin
    AdminMailer.delay.notice_consignment(self)
  end

  def each_name
    self.consignment_products.map(&:name).join("、")
  end
end

app/controllers/admin/consignments_controller.rb
#encoding: utf-8
class Admin::ConsignmentsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin

  def index
    @consignments = Consignment.paginate(page: params[:page])
  end

  def edit
    @consignment = Consignment.find(params[:id])
  end

  def update
    @consignment = Consignment.find(params[:id])

    if @consignment.update_attributes(params[:consignment])
      redirect_to admin_consignments_path, notice: '託售單更新成功'
    else
      render :edit
    end
  end

  def show
    @consignment = Consignment.find(params[:id])
    @products = @consignment.consignment_products.paginate(page: params[:page])
  end

end

app/controllers/consignments_controller.rb
#encoding: utf-8
class ConsignmentsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @consignments = current_user.consignments.paginate(page: params[:page])
  end

  def show
    @consignment = current_user.consignments.find(params[:id])
    @products = @consignment.consignment_products.paginate(page: params[:page])
  end

  def edit
    @consignment = current_user.consignments.find(params[:id])
  end

  def update
    @consignment = current_user.consignments.find(params[:id])
    if @consignment.update_attributes(params[:consignment].slice(:name,
                                                                 :chinese_name,
                                                                 :address,
                                                                 :phone,
                                                                 :attachment,
                                                                 :bank,
                                                                 :bank_num,
                                                                 :account,
                                                                 :account_num))
      redirect_to consignments_path, notice: '託售單更新成功!'
    else
      render :edit
    end
  end

  def new
    @consignment = current_user.consignments.build
    @consignment.consignment_products.build
  end

  def create
    @consignment = current_user.consignments.build(params[:consignment].
                                                   slice(:consignment_products_attributes,
                                                         :chinese_name,
                                                         :address,
                                                         :phone,
                                                         :bank,
                                                         :bank_num,
                                                         :account,
                                                         :account_num))
    @consignment.status = 'waiting'
    if @consignment.save
      redirect_to consignments_path, notice: '託售單新增成功'
    else
      render :new
    end
  end

end

app/helpers/consignments_helper.rb
#endcoding: utf-8
module ConsignmentsHelper

  def collection_for_consignment_status
    Consignment::STATUS.map { |value|
      [t(value), value]
    }
  end

  def show_consignment_product_dealing_link(consignment_product)
    case consignment_product.dealing_status
    when 'released'
      link_to consignment_product.product_name, product_path(consignment_product.product), target: '_blank', class: 'btn btn-mini btn-success'
    when 'pending_to_deal'
      link_to('轉為商品', new_admin_consignment_product_product_path(consignment_product), class: 'btn btn-mini btn-success') + " | " +link_to('拒絕', admin_consignment_product_deny_path(consignment_product), method: :put, class: 'btn btn-mini btn-danger')
    end
  end

  def billing_class(product)
    if product.can_billing?
      'blue'
    end
  end

  def render_billing_btn(consignment_product)
    return unless consignment_product.can_billing?
    link_to '請款', consignment_product_billing_path(consignment_product)
  end

  def render_product_link_for_consignment_product(consignment_product)
    if consignment_product.released?
      link_to "#{consignment_product.product_name}(#{currency_format consignment_product.product_price})", product_path(consignment_product.product)
    end
  end

end

app/views/admin/consignments/_consignment_product_fields.html.slim
.nested-fields.well
  = f.input :name, label: '商品名稱', hint: '請輸入欲託售的商品名稱'
  = f.input :brand, label: '品牌'
  = f.input :path, label: '購買通路'
  = f.input :warranty, label: '是否還在保固狀態？'
  = f.input :guarantee, label: '是否附保證書'
  = f.input :price, label: '欲託售價格'
  = f.input :how_new, label: '物品狀態', as: :radio_buttons, collection: ConsignmentProduct::HOW_NEW_STATUS, include_blank: false, :item_wrapper_class => 'inline'
  = f.input :short_coming, label: '汙損/故障處說明', input_html: { rows: 5, class: 'span8' }
  = f.input :comment, label: '備註', input_html: { rows: 5, class: 'span8' }
  = f.input :attachment, label: '照片(非必填)'

app/views/admin/consignments/edit.html.slim
#edit_consignment.span12
  .row-fluid
    .page-header
      h1 修改託售單
    = simple_form_for [:admin, @consignment], html: { class: 'form-horizontal' } do |f|
      #consignment_names
        = f.simple_fields_for :consignment_products, :wrapper => 'bootstrap' do |product|
          = render 'consignment_product_fields', f: product
        .controls
          = link_to_add_association '增加一筆商品', f, :consignment_products, class: 'btn btn-success btn-mini add-consignment-name', render_options: { wrapper: 'bootstrap' }
      hr
      = f.input :address, label: '地址'
      = f.input :chinese_name, label: '中文姓名'
      = f.input :phone, label: '電話'
      = f.input :bank, label: '銀行'
      = f.input :bank_num, label: '銀行代號', input_html: { class: 'span6', value: current_user.bank_num }
      = f.input :account, label: '戶名', input_html: { class: 'span6', value: current_user.account }
      = f.input :account_num, label: '帳號', input_html: { class: 'span6', value: current_user.account_num }
      .form-actions
        = f.submit '送出', class: 'btn btn-primary'

app/views/admin/consignments/index.html.slim
.consignments.span12
  .row-fluid
    table.table.table-striped.table-bordered.table-hover.table-condensed
      thead
        tr
          th 託售單編號
          th 託售物品
          th 申請託售時間
          th 操作
      tbody
        - @consignments.each do |consignment|
          tr
            td= consignment.id
            td= link_to consignment.each_name, admin_consignment_path(consignment)
            td= l consignment.created_at, format: :short
            td= link_to '編輯', edit_admin_consignment_path(consignment)
  .row-fluid
    = will_paginate @consignments

app/views/admin/consignments/show.html.slim
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container style="width: auto;"
            a.brand href="#" 商品列表
      #consignment_products_wrapper
        table.table.table-bordered.table-hover.table-condensed
          thead
            tr
              th 託售物品
              th 品牌
              th 購買通路
              th 是否保固
              th 保證書
              th 欲託售價格
              th 商品狀態
              th 故障/汙損說明
              th 備註
              th 附件
              th 處理狀態
              th 上架商品
          tbody
            - @products.each do |product|
              tr
                td= product.name
                td= product.brand
                td= product.path
                td= product.warranty
                td= product.guarantee
                td= product.price
                td= product.how_new
                td= product.short_coming
                td= product.comment
                - if product.attachment.present?
                  td= link_to "下載", product.attachment_url
                - else
                  td
                td= ConsignmentProduct::DEALING_STATUS[product.dealing_status]
                td= show_consignment_product_dealing_link(product)
      = will_paginate @products