config/routes.rb
Babysworld::Application.routes.draw do
  root :to => "products#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :skip => [:sessions], controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get '/about', to: 'welcome#about'
  get '/terms', to: 'welcome#terms'
  get '/user_consignment', to: 'welcome#user_consignment'
  get '/consignment_about', to: 'welcome#consignment_about'
  get '/faq', to: 'welcome#faq'
  get '/robots.txt', to: 'welcome#robots'

  get 'tags/:tag', to: 'products#index', as: :tag

  namespace :admin do
    resources :products do
      put '/release', to: 'products#release'
      put '/waiting_for_money', to: 'products#waiting_for_money'
      put '/sold', to: 'products#sold'
    end
    resources :banners
    resources :consignments
    resources :consignment_products do
      put '/deny', to: 'consignment_products#deny'
      resources :products, controller: 'consignment_products/products'
    end
    resources :billings
  end

  resources :users, only: [:edit, :update] do
    resources :billings, only: [:create, :index]
  end

  resources :billings do
    resources :consignment_products, only: [:index]
  end

  resources :products, :only => [:index, :show]

  resources :consignments
  resources :consignment_products do
    put '/billing', to: 'consignment_products#billing'
  end

end

app/models/product.rb
#encoding: utf-8
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :original_price, :price, :ruten_no, :user,
                  :status, :product_images_attributes, :pattern, :notice,
                  :category_id, :tag_list
  belongs_to :user
  belongs_to :category
  has_many :product_images, :dependent => :destroy
  accepts_nested_attributes_for :product_images, :reject_if => :all_blank, :allow_destroy => true
  validates_presence_of :name, :description, :user, :price,
                        :ruten_no
  acts_as_taggable
  has_one :consignment_product
  delegate :name, to: :consignment_product, allow_nil: true, prefix: true
  validate :at_least_one_image

  default_scope :order => 'created_at desc'

  STATUS =  {
             "waiting_for_review" => "等待上架",
             "released" => "已上架",
             "replenish" => "補貨中",
             "checked_out" => "已售出"
            }

  state_machine :status, :initial => :waiting_for_review do
    event :release do
      transition [:waiting_for_review, :replenish] => :released
    end

    event :waiting_for_money do
      transition :released => :replenish
    end

    event :sold do
      transition :replenish => :checked_out
    end

    after_transition [:waiting_for_review, :replenish] => :released do |product|
      product.consignment_product.release if product.consignment_product.present?
    end

    after_transition :released => :replenish do |product|
      product.consignment_product.ordered if product.consignment_product.present?
    end

    after_transition :replenish => :checked_out do |product|
      product.consignment_product.sold if product.consignment_product.present?
    end

  end

  extend Category::FindByCategoryScope

  validates_inclusion_of :status, :in => STATUS.keys

  scope :available, where(:status => ["released", "replenish"])

  def url
    "http://goods.ruten.com.tw/item/show?#{self.ruten_no}"
  end

  def self.search(query)
    where("name LIKE ? OR description LIKE ?", "%#{query}%", "%#{query}%")
  end

  private

  def at_least_one_image
    errors.add(:product_images, "至少要有一張圖片") if product_images.length == 0
  end
end

app/controllers/admin/consignment_products/products_controller.rb
#encoding: utf-8
class Admin::ConsignmentProducts::ProductsController < ApplicationController
  before_filter :authenticate_admin
  layout 'admin'

  def new
    @consignment_product = ConsignmentProduct.find(params[:consignment_product_id])
    @product = @consignment_product.to_product
  end

  def create
    consignment_product = ConsignmentProduct.find(params[:consignment_product_id])
    @product = consignment_product.build_product(params[:product])
    @product.user = current_user
    if @product.save
      consignment_product.save
      redirect_to admin_products_path, notice: '建立成功'
    else
      render :new, error: @product.errors
    end
  end
end

app/controllers/admin/products_controller.rb
#encoding: utf-8
class Admin::ProductsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin

  def index
    @products = Product.paginate(:page => params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = current_user.products.build
    @product.product_images.build
  end

  def create
    @product = current_user.products.build(params[:product])

    if @product.save
      redirect_to admin_products_path, :notice => "商品建立成功"
    else
      ap @product.errors
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(params[:product])
      redirect_to admin_products_path, :notice => "商品修改成功"
    else
      render :edit
    end
  end

  def release
    @product = Product.find(params[:product_id])
    if @product.release
      redirect_to admin_products_path, notice: '商品狀態變更為已上架'
    else
      redirect_to admin_products_path, error: "商品狀態變更失敗，原因:#{@product.errors}"
    end
  end

  def waiting_for_money
    @product = Product.find(params[:product_id])
    if @product.waiting_for_money
      redirect_to admin_products_path, notice: '商品狀態變更為補貨中'
    else
      redirect_to admin_products_path, error: "商品狀態變更失敗，原因:#{@product.errors}"
    end
  end

  def sold
    @product = Product.find(params[:product_id])
    if @product.sold
      redirect_to admin_products_path, notice: '商品狀態變更為已售出'
    else
      redirect_to admin_products_path, error: "商品狀態變更失敗，原因:#{@product.errors}"
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    if params[:tag]
      @products = Product.available.tagged_with(params[:tag]).paginate(:page => params[:page])
    elsif params[:search]
      @products = Product.available.search(params[:search]).paginate(:page => params[:page], per_page: 15)
    else
      @products = Product.available.paginate(:page => params[:page], per_page: 15)
    end
    @banners = Banner.available
  end

  def show
    @product = Product.available.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def currency_format(amount)
    number_to_currency amount, precision: 0
  end

  def render_product_btn(product)
    case product.status
    when 'waiting_for_review'
      then link_to '上架', admin_product_release_path(product), method: :put, class: 'btn btn-mini btn-success'
    when 'released'
      then link_to('補貨', admin_product_waiting_for_money_path(product), method: :put, class: 'btn btn-mini btn-success')
    when 'replenish'
      then link_to('售出', admin_product_sold_path(product), method: :put, class: 'btn btn-mini btn-success')+ " | " + link_to('重新上架', admin_product_release_path(product), method: :put, class: 'btn btn-mini btn-primary')
    else
      ""
    end
  end
end

app/views/products/_products.html.slim
- products.each_slice(3) do |a, b, c|
  ul.thumbnails.products
    = div_for a, :class => "product span4" do
      .thumbnail
        - if a.product_images.size > 0
          .product-image
            = link_to(image_tag(a.product_images.first.image.url(:thumb)), product_path(a))
        - else
          = link_to(image_tag("http://placekitten.com/g/200/200"), product_path(a))
        .caption
          h4= link_to a.name, product_path(a)
          span.price $ #{a.price}
          - if a.status != 'replenish'
            = link_to a.url, :target => "_blank", :class => 'btn' do
                i.icon-shopping-cart
                '
                | 買下來
          - else
            a.btn.btn-danger.disabled href="javascript:;" 補貨中
          .clearfix
    - if b
      = div_for b, :class => "product span4" do
        .thumbnail
          - if b.product_images.size > 0
            .product-image
              = link_to(image_tag(b.product_images.first.image.url(:thumb)), product_path(b))
          - else
            = link_to(image_tag("http://placekitten.com/g/200/200"), product_path(b))
          .caption
            h4= link_to b.name, product_path(b)
            span.price $ #{b.price}
            - if b.status != 'replenish'
              = link_to b.url, :target => "_blank", :class => 'btn' do
                i.icon-shopping-cart
                '
                | 買下來
            - else
              a.btn.btn-danger.disabled href="javascript:;" 補貨中
            .clearfix
    - if c
      = div_for c, :class => "product span4" do
        .thumbnail
          - if c.product_images.size > 0
            .product-image
              = link_to(image_tag(c.product_images.first.image.url(:thumb)), product_path(c))
          - else
            = link_to(image_tag("http://placekitten.com/g/200/200"), product_path(c))
          .caption
            h4= link_to c.name, product_path(c)
            span.price $ #{c.price}
            - if c.status != 'replenish'
              = link_to c.url, :target => "_blank", :class => 'btn' do
                i.icon-shopping-cart
                '
                | 買下來
            - else
              a.btn.btn-danger.disabled href="javascript:;" 補貨中
          .clearfix

app/views/products/index.html.slim
- title '商品列表'
- description '寶寶世界二手屋有最多的寶寶二手商品，所有販售的商品都經過寶寶世界二手屋的專業清潔與認證，讓爸爸媽媽們買的放心、用的安心'
/#productsCarousel.carousel.slide.span12
  /! Carousel items
  .carousel-inner
    - @banners.each_with_index do |banner, index|
      - if index == 0
        .item.active
          = link_to image_tag(banner.banner.url), banner.url, target: "_blank"
      - else
        .item
          = link_to image_tag(banner.banner.url), banner.url, target: "_blank"

  /! Carousel nav
  /a.carousel-control.left href="#productsCarousel" data-slide="prev" &lsaquo;
  /a.carousel-control.right href="#productsCarousel" data-slide="next" &rsaquo;
= image_tag('banner.jpg', class: 'banner')

.sidebar.span3
  .row-fluid
    = form_tag products_path, method: :get, class: 'form-search' do
      = text_field_tag :search, params[:search], class: 'search-query span12'
      .icon-search
  .clearfix
  = render "shared/tags_aside"
.products.span9
  #title-nav.navbar
    .navbar-inner
      a.brand 最新上架商品
  .row-fluid
    = render partial: "products", locals: { products: @products }
  = will_paginate @products

app/views/products/show.html.slim
- title @product.name
- description @product.description
.sidebar.span3
  = render 'shared/tags_aside'
.product.span9
  header.page-header
    h1= @product.name
  .row
    - if @product.product_images.size <= 1
      .span6
        = image_tag(@product.product_images.first.image.url(:product))
    - else
      #productCarousel.carousel.slide.span6
        /! Carousel items
        .carousel-inner
          - @product.product_images.each_with_index do |image, index|
            - if index == 0
              .item.active
                = image_tag(image.image.url(:product))
            - else
              .item
                = image_tag(image.image.url(:product))
        /! Carousel nav
        a.carousel-control.left href="#productCarousel" data-slide="prev" &lsaquo;
        a.carousel-control.right href="#productCarousel" data-slide="next" &rsaquo;
    .product-main.span3
      .well.info-block
        - if @product.original_price != 0
          h2.capton.pull-left 市價
          h2
            del.orignal_price.pull-right= number_to_currency @product.original_price, :precision => 0
        .clearfix
        h2.capton.pull-left 售價
        h2.price.pull-right= number_to_currency @product.price, :precision => 0
        .clearfix
        - if @product.status != 'replenish'
          = link_to @product.url, :class => 'btn btn-primary btn-large', id: 'shop-btn', :target => "_blank" do
            i.icon-shopping-cart
            = " 購買"
        - else
          a.btn.btn-danger.btn-large.disabled#shop-btn href="javascript:;" 補貨中
        .clearfix
  .tabbable
    ul.nav.nav-tabs
      li.active
        a href="#product-description" data-toggle="tab" 商品描述
      - if @product.description.present?
        li
          a href="#product-notice" data-toggle="tab" 注意事項
    .tab-content
      .tab-pane.active.fade.in#product-description
        = simple_format @product.description
      - if @product.description.present?
        .tab-pane.fade#product-notice
          = simple_format @product.notice
  .disinfection-statement.alert.alert-success
    = render "shared/disinfection"
  .alert
    h4.alert-heading 購物需知
    span 由於網路的普及已形成了許多新型態的網路詐騙，為了維護網路交易安全，本網站目前只提供託售會員進行託售商品查詢，網站商品頁並無直接購物功能。
    br
    span 如需購物請至寶寶世界二手屋在露天拍賣的賣場，藉由大型的網路平台來降低網路詐騙的風險。
    br
    span 露天拍賣的賣家帳號：
    '
    a href="http://class.ruten.com.tw/user/index00.php?s=babysworld" babysworld
    br
    span 賣場名稱：
    '
    a href="http://class.ruten.com.tw/user/index00.php?s=babysworld" 寶寶世界二手屋